### ISSUE TITLE
Support for comments

### ISSUE THREAD

**Issue by royaldark** [utkarshkukreti/edn.rs#4]
Hi, first of all thank you for making this awesome library! As someone still learning Rust, it's been a complete breeze to work with and I've learned a lot!

Looks like currently the parser tosses an `unimplemented!` when encountering a line starting with `;`. Per [the EDN spec](https://github.com/edn-format/edn#comments), 

> "If a ; character is encountered outside of a string, that character and all subsequent characters to the next newline should be ignored.

What would be involved in adding support for comments? Since comments are line-level and exist independently of S-expressions, I guess support would have to be added to the handling of each existing EDN type? And maybe a new branch in the `match` to support comments which occur outside of any other form (e.g. beginning of file)?

**Comment by utkarshkukreti** [comment]
Comments are ignored by the official EDN parser right? What do you think about https://github.com/utkarshkukreti/edn.rs/commit/1556126e3f5b31b2e93877a21bfcece5220d9ca0? (I've only tested a couple of examples right now.)

**Comment by utkarshkukreti** [comment]
> As a side note, would you consider replacing panics in the parser with an Error value of some kind? 

Yes, definitely. Not sure why I went with panicking, but if I wrote this today, I'd never panic. I'd suggest replacing all the 4 `unimplemented!` to return an "unknown error" with whatever relevant span can be extracted. A test for each of the 4 cases would be wonderful! :)

**Comment by utkarshkukreti** [comment]
Please try out https://github.com/utkarshkukreti/edn.rs/commit/eaeaab8fbadaa0e39ce8e73f7ccc18e61f898e50.

Happy to accept PR for changing all panics to returning errors!

**Comment by royaldark** [comment]
`eaeaab8` works for every test case I threw at it!
